//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsWCF.WCFService1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WebAdd", ReplyAction="http://tempuri.org/IService/WebAddResponse")]
        int WebAdd(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WebAdd", ReplyAction="http://tempuri.org/IService/WebAddResponse")]
        System.Threading.Tasks.Task<int> WebAddAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WebSoustraction", ReplyAction="http://tempuri.org/IService/WebSoustractionResponse")]
        int WebSoustraction(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WebSoustraction", ReplyAction="http://tempuri.org/IService/WebSoustractionResponse")]
        System.Threading.Tasks.Task<int> WebSoustractionAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WebMultiply", ReplyAction="http://tempuri.org/IService/WebMultiplyResponse")]
        int WebMultiply(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WebMultiply", ReplyAction="http://tempuri.org/IService/WebMultiplyResponse")]
        System.Threading.Tasks.Task<int> WebMultiplyAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WebDivision", ReplyAction="http://tempuri.org/IService/WebDivisionResponse")]
        int WebDivision(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WebDivision", ReplyAction="http://tempuri.org/IService/WebDivisionResponse")]
        System.Threading.Tasks.Task<int> WebDivisionAsync(int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WindowsFormsWCF.WCFService1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WindowsFormsWCF.WCFService1.IService>, WindowsFormsWCF.WCFService1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int WebAdd(int x, int y) {
            return base.Channel.WebAdd(x, y);
        }
        
        public System.Threading.Tasks.Task<int> WebAddAsync(int x, int y) {
            return base.Channel.WebAddAsync(x, y);
        }
        
        public int WebSoustraction(int x, int y) {
            return base.Channel.WebSoustraction(x, y);
        }
        
        public System.Threading.Tasks.Task<int> WebSoustractionAsync(int x, int y) {
            return base.Channel.WebSoustractionAsync(x, y);
        }
        
        public int WebMultiply(int x, int y) {
            return base.Channel.WebMultiply(x, y);
        }
        
        public System.Threading.Tasks.Task<int> WebMultiplyAsync(int x, int y) {
            return base.Channel.WebMultiplyAsync(x, y);
        }
        
        public int WebDivision(int x, int y) {
            return base.Channel.WebDivision(x, y);
        }
        
        public System.Threading.Tasks.Task<int> WebDivisionAsync(int x, int y) {
            return base.Channel.WebDivisionAsync(x, y);
        }
    }
}
